clear;
clc;
close all;

%% =========================================================
%  เลือกไฟล์ข้อมูล
% ==========================================================

filename = 'AMT103_X4_CW_1.xlsx';

if ~isfile(filename)

    error('ไม่พบไฟล์ %s ใน MATLAB Current Folder',filename);

end

%% =========================================================
%  อ่านข้อมูลจาก Excel
% ==========================================================

T = readtable(filename,...
    'VariableNamingRule','preserve');

%% ตรวจสอบคอลัมน์ที่ต้องใช้

requiredColumns = {
    'time'
    'continuous_count'
    'homed_count'
    'home_trigger'
};

for i = 1:length(requiredColumns)

    if ~ismember(...
            requiredColumns{i},...
            T.Properties.VariableNames)

        error(...
            'ไม่พบคอลัมน์ %s ในไฟล์ %s',...
            requiredColumns{i},...
            filename);
    end
end

%% แปลงข้อมูลเป็น Double

time = double(T.time);

continuousCount = double(...
    T.continuous_count);

homedCount = double(...
    T.homed_count);

homeTrigger = double(...
    T.home_trigger);

%% =========================================================
%  หาจุดเริ่มต้นและสิ้นสุดการกด Home
% ==========================================================

% ตรวจจับขอบขาขึ้นของ Home trigger
homeRisingEdge = find(...
    diff([0; homeTrigger]) > 0.5);

if isempty(homeRisingEdge)

    error('ไม่พบการกด Home ในไฟล์ %s',filename);

end

% ใช้การกด Home ครั้งสุดท้าย
idxHomeStart = homeRisingEdge(end);

% ตรวจจับขอบขาลงหลังจากกด Home
homeFallingEdge = find(...
    diff([homeTrigger; 0]) < -0.5);

% เลือกขอบขาลงที่อยู่หลังจุดเริ่ม Home
idxHomeEndList = homeFallingEdge(...
    homeFallingEdge >= idxHomeStart);

if isempty(idxHomeEndList)

    % หากไม่พบขอบขาลง ให้ใช้จุดเริ่ม Home แทน
    idxHomeEnd = idxHomeStart;

else

    idxHomeEnd = idxHomeEndList(1);

end

%% แสดงข้อมูลตรวจสอบ

fprintf('Home เริ่มที่เวลา %.3f s\n',...
    time(idxHomeStart));

fprintf('Home สิ้นสุดที่เวลา %.3f s\n',...
    time(idxHomeEnd));

fprintf('Continuous count ก่อน Home = %.0f\n',...
    continuousCount(max(1,idxHomeStart-1)));

fprintf('Homed count ก่อน Home = %.0f\n',...
    homedCount(max(1,idxHomeStart-1)));

fprintf('Continuous count ขณะ Home = %.0f\n',...
    continuousCount(idxHomeStart));

fprintf('Homed count ขณะ Home = %.0f\n',...
    homedCount(idxHomeStart));

%% =========================================================
%  เลือกช่วงข้อมูลสำหรับพล็อต
% ==========================================================

% Sample time ประมาณ 0.001 s
% แสดง 2 วินาทีก่อน Home และ 6 วินาทีหลังปล่อย Home

samplesBefore = 2000;
samplesAfter  = 6000;

idxStart = max(1,...
    idxHomeStart-samplesBefore);

idxEnd = min(height(T),...
    idxHomeEnd+samplesAfter);

idxPlot = idxStart:idxEnd;

%% ทำให้เวลา Home เริ่มที่ t = 0

plotTime = time(idxPlot)-time(idxHomeStart);

continuousPlot = continuousCount(idxPlot);

homedPlot = homedCount(idxPlot);

triggerPlot = homeTrigger(idxPlot);

% เวลาที่ปล่อยปุ่ม Home เทียบกับเวลาเริ่มกด
releaseTime = ...
    time(idxHomeEnd)-time(idxHomeStart);

%% =========================================================
%  สร้าง Figure
% ==========================================================

fig = figure(...
    'Color','white',...
    'InvertHardcopy','off',...
    'Position',[100 70 1150 750]);

tl = tiledlayout(fig,2,1,...
    'Padding','compact',...
    'TileSpacing','compact');

%% =========================================================
%  กราฟ Continuous Count และ Homed Count
% ==========================================================

ax1 = nexttile(tl,1);

plot(...
    ax1,...
    plotTime,...
    continuousPlot,...
    'Color',[0.85 0.10 0.10],...
    'LineWidth',1.8,...
    'DisplayName','Continuous count');

hold(ax1,'on');

plot(...
    ax1,...
    plotTime,...
    homedPlot,...
    'Color',[0.00 0.30 0.90],...
    'LineWidth',1.8,...
    'DisplayName','Homed count');

% เส้นเริ่มกด Home
xline(...
    ax1,...
    0,...
    '--k',...
    'Home ON',...
    'LineWidth',1.3,...
    'HandleVisibility','off',...
    'LabelVerticalAlignment','bottom');

% เส้นปล่อยปุ่ม Home
if releaseTime > 0

    xline(...
        ax1,...
        releaseTime,...
        ':k',...
        'Home OFF',...
        'LineWidth',1.3,...
        'HandleVisibility','off',...
        'LabelVerticalAlignment','bottom');

end

% เส้น Count = 0
yline(...
    ax1,...
    0,...
    ':k',...
    'Count = 0',...
    'LineWidth',1.0,...
    'HandleVisibility','off');

title(...
    ax1,...
    'AMT103 X4: Homing Sequence',...
    'Color','black',...
    'FontSize',14,...
    'FontWeight','bold');

xlabel(...
    ax1,...
    'Time relative to Home ON (s)',...
    'Color','black',...
    'FontSize',12);

ylabel(...
    ax1,...
    'Count',...
    'Color','black',...
    'FontSize',12);

lgd1 = legend(...
    ax1,...
    'Location','best');

set(...
    lgd1,...
    'Color','white',...
    'TextColor','black',...
    'EdgeColor','black',...
    'FontSize',11);

grid(ax1,'on');
grid(ax1,'minor');
box(ax1,'on');

%% =========================================================
%  กราฟ Home Trigger
% ==========================================================

ax2 = nexttile(tl,2);

stairs(...
    ax2,...
    plotTime,...
    triggerPlot,...
    'Color',[0.10 0.60 0.10],...
    'LineWidth',2.0,...
    'DisplayName','Home trigger');

hold(ax2,'on');

% เส้นเริ่มกด Home
xline(...
    ax2,...
    0,...
    '--k',...
    'Home ON',...
    'LineWidth',1.3,...
    'HandleVisibility','off',...
    'LabelVerticalAlignment','bottom');

% เส้นปล่อยปุ่ม Home
if releaseTime > 0

    xline(...
        ax2,...
        releaseTime,...
        ':k',...
        'Home OFF',...
        'LineWidth',1.3,...
        'HandleVisibility','off',...
        'LabelVerticalAlignment','bottom');

end

title(...
    ax2,...
    'Home Trigger State',...
    'Color','black',...
    'FontSize',14,...
    'FontWeight','bold');

xlabel(...
    ax2,...
    'Time relative to Home ON (s)',...
    'Color','black',...
    'FontSize',12);

ylabel(...
    ax2,...
    'Digital state',...
    'Color','black',...
    'FontSize',12);

ylim(ax2,[-0.2 1.2]);

yticks(ax2,[0 1]);

yticklabels(ax2,...
    {'LOW','HIGH'});

grid(ax2,'on');
grid(ax2,'minor');
box(ax2,'on');

%% =========================================================
%  ตั้งค่าพื้นหลังและตัวหนังสือ
% ==========================================================

set(...
    fig,...
    'Color','white',...
    'InvertHardcopy','off');

set(...
    ax1,...
    'Color','white',...
    'XColor','black',...
    'YColor','black',...
    'GridColor',[0.70 0.70 0.70],...
    'MinorGridColor',[0.85 0.85 0.85],...
    'FontSize',11);

set(...
    ax2,...
    'Color','white',...
    'XColor','black',...
    'YColor','black',...
    'GridColor',[0.70 0.70 0.70],...
    'MinorGridColor',[0.85 0.85 0.85],...
    'FontSize',11);

ax1.Title.Color = 'black';
ax1.XLabel.Color = 'black';
ax1.YLabel.Color = 'black';

ax2.Title.Color = 'black';
ax2.XLabel.Color = 'black';
ax2.YLabel.Color = 'black';

%% เชื่อมแกนเวลา

linkaxes([ax1 ax2],'x');

%% =========================================================
%  บันทึกภาพ
% ==========================================================

outputName = 'AMT103_X4_Homing.png';

exportgraphics(...
    fig,...
    outputName,...
    'Resolution',300,...
    'BackgroundColor','white');

fprintf('บันทึกภาพแล้ว: %s\n',outputName);