clear;
clc;
close all;

%% =========================================================
%  ตั้งค่า Encoder และชื่อไฟล์
% ==========================================================

% BOURNS
config(1).name = 'BOURNS';
config(1).slowPattern = 'BOURNS_X4_SPEED_SLOW_%d.xlsx';
config(1).fastPattern = 'BOURNS_X4_SPEED_FAST_%d.xlsx';
config(1).CPR = 24*4;                  % 96 counts/rev

% AMT103
config(2).name = 'AMT103';
config(2).slowPattern = 'AMT103_X4_SLOW_%d.xlsx';
config(2).fastPattern = 'AMT103_X4_FAST_%d.xlsx';
config(2).CPR = 2048*4;                % 8192 counts/rev

%% สีเส้นแต่ละรอบ

slowColors = [
    0.00 0.20 0.70
    0.00 0.45 0.90
    0.30 0.70 1.00
];

fastColors = [
    0.75 0.00 0.00
    0.95 0.20 0.05
    1.00 0.50 0.10
];

%% =========================================================
%  สร้างกราฟให้ Encoder แต่ละชนิด
% ==========================================================

for e = 1:length(config)

    % สำหรับเก็บผลคำนวณความเร็วแต่ละรอบ
    speedSlow = zeros(1,3);
    speedFast = zeros(1,3);

    durationSlow = zeros(1,3);
    durationFast = zeros(1,3);

    %% สร้าง Figure

    fig = figure(...
        'Color','white',...
        'InvertHardcopy','off',...
        'Position',[100 50 1200 800]);

    tl = tiledlayout(fig,2,1,...
        'Padding','compact',...
        'TileSpacing','compact');

    %% กราฟ Angular Position

    axPosition = nexttile(tl,1);

    hold(axPosition,'on');
    grid(axPosition,'on');
    grid(axPosition,'minor');
    box(axPosition,'on');

    maxDuration = 0;

    %% =====================================================
    %  อ่านข้อมูล Slow และ Fast
    % ======================================================

    for condition = 1:2

        if condition == 1

            filePattern = config(e).slowPattern;
            conditionName = 'Slow';
            colors = slowColors;

        else

            filePattern = config(e).fastPattern;
            conditionName = 'Fast';
            colors = fastColors;

        end

        %% อ่านรอบที่ 1–3

        for r = 1:3

            filename = sprintf(filePattern,r);

            fprintf('กำลังอ่าน: %s\n',filename);

            T = readtable(filename,...
                'VariableNamingRule','preserve');

            %% ตรวจสอบคอลัมน์

            requiredColumns = {
                'time'
                'home_trigger'
                'homed_count'
            };

            for columnNumber = 1:length(requiredColumns)

                if ~ismember(...
                        requiredColumns{columnNumber},...
                        T.Properties.VariableNames)

                    error(...
                        'ไม่พบคอลัมน์ %s ในไฟล์ %s',...
                        requiredColumns{columnNumber},...
                        filename);
                end
            end

            %% หาจุดสุดท้ายที่กด Home

            idxHome = find(...
                T.home_trigger == 1,...
                1,...
                'last');

            if isempty(idxHome)

                % ถ้าไม่มี Home ให้ใช้ข้อมูลตั้งแต่ต้นไฟล์
                warning(...
                    'ไม่พบ home_trigger ในไฟล์ %s ใช้ข้อมูลตั้งแต่ต้นแทน',...
                    filename);

                idxData = 1:height(T);

            else

                % ถ้ามี Home ให้เริ่มจากตัวอย่างถัดไป
                idxData = idxHome+1:height(T);

            end

            if isempty(idxData)

                error(...
                    'ไม่มีข้อมูลสำหรับวิเคราะห์ในไฟล์ %s',...
                    filename);
            end

            %% อ่านเวลาและ Count

            time = double(T.time(idxData));
            count = double(T.homed_count(idxData));

            % ทำให้ Count เริ่มจากศูนย์
            count = count-count(1);

            %% หาช่วงที่ Encoder กำลังเคลื่อนที่

            countDifference = diff(count);

            movementIndex = find(countDifference ~= 0);

            if isempty(movementIndex)

                warning(...
                    'ไม่พบการเคลื่อนที่ในไฟล์ %s',...
                    filename);

                continue;
            end

            idxStart = movementIndex(1);
            idxEnd = movementIndex(end)+1;

            %% ตัดเฉพาะช่วงเคลื่อนที่

            time = time(idxStart:idxEnd);
            count = count(idxStart:idxEnd);

            % ทำให้เวลาและ Count เริ่มจากศูนย์
            time = time-time(1);
            count = count-count(1);

            %% แปลง Count เป็นองศา

            degree = abs(count)*360/config(e).CPR;

            %% คำนวณเวลาและความเร็วเฉลี่ย

            totalDuration = time(end);

            finalAngleDegree = degree(end);
            finalAngleRad = deg2rad(finalAngleDegree);

            averageAngularVelocity = ...
                finalAngleRad/totalDuration;

            if condition == 1

                durationSlow(r) = totalDuration;
                speedSlow(r) = averageAngularVelocity;

            else

                durationFast(r) = totalDuration;
                speedFast(r) = averageAngularVelocity;

            end

            maxDuration = max(maxDuration,totalDuration);

            %% พล็อต Angular Position

            if strcmp(config(e).name,'BOURNS')

                % BOURNS ใช้ stairs เพราะความละเอียดต่ำ
                stairs(...
                    axPosition,...
                    time,...
                    degree,...
                    'Color',colors(r,:),...
                    'LineWidth',1.5,...
                    'HandleVisibility','off');

            else

                % AMT103 ใช้ plot เพราะความละเอียดสูง
                plot(...
                    axPosition,...
                    time,...
                    degree,...
                    'Color',colors(r,:),...
                    'LineWidth',1.5,...
                    'HandleVisibility','off');
            end

            %% แสดงผลใน Command Window

            fprintf(...
                '%s %s รอบ %d: Count = %.0f, มุม = %.2f°, เวลา = %.3f s, ความเร็วเฉลี่ย = %.4f rad/s\n',...
                config(e).name,...
                conditionName,...
                r,...
                abs(count(end)),...
                finalAngleDegree,...
                totalDuration,...
                averageAngularVelocity);
        end
    end

    %% =====================================================
    %  Legend แบบสั้นสำหรับ Position
    % ======================================================

    hSlow = plot(...
        axPosition,...
        NaN,...
        NaN,...
        'Color',[0.00 0.35 0.90],...
        'LineWidth',2.5,...
        'DisplayName','Slow');

    hFast = plot(...
        axPosition,...
        NaN,...
        NaN,...
        'Color',[0.90 0.10 0.00],...
        'LineWidth',2.5,...
        'DisplayName','Fast');

    %% เส้นค่าทฤษฎี 360°

    hTheory = yline(...
        axPosition,...
        360,...
        '--k',...
        '360°',...
        'LineWidth',1.2,...
        'HandleVisibility','off');

    hTheory.FontSize = 11;
    hTheory.FontWeight = 'bold';
    hTheory.LabelHorizontalAlignment = 'right';
    hTheory.LabelVerticalAlignment = 'bottom';

    %% จัดรูปแบบ Angular Position

    title(...
        axPosition,...
        sprintf(...
            '%s X4: Angular Position — Slow vs Fast',...
            config(e).name),...
        'Color','black',...
        'FontSize',14,...
        'FontWeight','bold');

    xlabel(...
        axPosition,...
        'Time (s)',...
        'Color','black',...
        'FontSize',12);

    ylabel(...
        axPosition,...
        'Angular position (degree)',...
        'Color','black',...
        'FontSize',12);

    xlim(axPosition,[0 maxDuration*1.05]);
    ylim(axPosition,[-10 390]);

    lgdPosition = legend(...
        axPosition,...
        [hSlow hFast],...
        {'Slow','Fast'},...
        'Location','southeast');

    set(...
        lgdPosition,...
        'Color','white',...
        'TextColor','black',...
        'EdgeColor','black',...
        'FontSize',11);

    %% =====================================================
    %  กราฟ Average Angular Velocity
    % ======================================================

    axSpeed = nexttile(tl,2);

    hold(axSpeed,'on');
    grid(axSpeed,'on');
    box(axSpeed,'on');

    meanSpeed = [
        mean(speedSlow)
        mean(speedFast)
    ];

    sdSpeed = [
        std(speedSlow)
        std(speedFast)
    ];

    %% กราฟแท่ง

    b = bar(...
        axSpeed,...
        1:2,...
        meanSpeed,...
        0.55,...
        'FaceColor','flat');

    b.CData = [
        0.00 0.35 0.90
        0.90 0.10 0.00
    ];

    %% Error bar

    errorbar(...
        axSpeed,...
        1:2,...
        meanSpeed,...
        sdSpeed,...
        'k.',...
        'LineWidth',1.5,...
        'CapSize',12);

    %% แสดงค่าของแต่ละรอบ

    jitter = [-0.08 0 0.08];

    scatter(...
        axSpeed,...
        1+jitter,...
        speedSlow,...
        55,...
        [0.00 0.20 0.70],...
        'filled',...
        'MarkerEdgeColor','black');

    scatter(...
        axSpeed,...
        2+jitter,...
        speedFast,...
        55,...
        [0.90 0.10 0.00],...
        'filled',...
        'MarkerEdgeColor','black');

    %% ใส่ค่าเฉลี่ยบนแท่ง

    text(...
        axSpeed,...
        1,...
        meanSpeed(1)+sdSpeed(1)+0.03*max(meanSpeed),...
        sprintf('%.3f rad/s',meanSpeed(1)),...
        'HorizontalAlignment','center',...
        'Color','black',...
        'FontWeight','bold');

    text(...
        axSpeed,...
        2,...
        meanSpeed(2)+sdSpeed(2)+0.03*max(meanSpeed),...
        sprintf('%.3f rad/s',meanSpeed(2)),...
        'HorizontalAlignment','center',...
        'Color','black',...
        'FontWeight','bold');

    %% จัดรูปแบบกราฟความเร็ว

    xticks(axSpeed,[1 2]);
    xticklabels(axSpeed,{'Slow','Fast'});

    xlim(axSpeed,[0.4 2.6]);

    maxY = max(meanSpeed+sdSpeed);

    if maxY > 0
        ylim(axSpeed,[0 maxY*1.30]);
    end

    title(...
        axSpeed,...
        sprintf(...
            '%s X4: Average Angular Velocity',...
            config(e).name),...
        'Color','black',...
        'FontSize',14,...
        'FontWeight','bold');

    xlabel(...
        axSpeed,...
        'Rotation condition',...
        'Color','black',...
        'FontSize',12);

    ylabel(...
        axSpeed,...
        'Average angular velocity (rad/s)',...
        'Color','black',...
        'FontSize',12);

    %% =====================================================
    %  บังคับพื้นหลังขาว
    % ======================================================

    set(...
        fig,...
        'Color','white',...
        'InvertHardcopy','off');

    set(...
        axPosition,...
        'Color','white',...
        'XColor','black',...
        'YColor','black',...
        'GridColor',[0.70 0.70 0.70],...
        'MinorGridColor',[0.85 0.85 0.85],...
        'FontSize',11);

    set(...
        axSpeed,...
        'Color','white',...
        'XColor','black',...
        'YColor','black',...
        'GridColor',[0.75 0.75 0.75],...
        'FontSize',11);

    axPosition.Title.Color = 'black';
    axPosition.XLabel.Color = 'black';
    axPosition.YLabel.Color = 'black';

    axSpeed.Title.Color = 'black';
    axSpeed.XLabel.Color = 'black';
    axSpeed.YLabel.Color = 'black';

    %% =====================================================
    %  บันทึกภาพ
    % ======================================================

    outputName = sprintf(...
        '%s_X4_Slow_vs_Fast.png',...
        config(e).name);

    exportgraphics(...
        fig,...
        outputName,...
        'Resolution',300,...
        'BackgroundColor','white');

    fprintf('\nบันทึกภาพแล้ว: %s\n',outputName);

    %% แสดงสรุปใน Command Window

    fprintf(...
        '%s Slow: Mean speed = %.4f rad/s, SD = %.4f\n',...
        config(e).name,...
        mean(speedSlow),...
        std(speedSlow));

    fprintf(...
        '%s Fast: Mean speed = %.4f rad/s, SD = %.4f\n\n',...
        config(e).name,...
        mean(speedFast),...
        std(speedFast));
end