clear;
clc;
close all;

%% =========================================================
%  เลือกไฟล์
% ==========================================================

% รองรับทั้งชื่อ CCW และ CWW
if isfile('AMT103_X4_CCW_3.xlsx')

    filename = 'AMT103_X4_CCW_3.xlsx';

elseif isfile('AMT103_X4_CWW_3.xlsx')

    filename = 'AMT103_X4_CWW_3.xlsx';

else

    error(['ไม่พบไฟล์ AMT103_X4_CCW_3.xlsx ',...
           'หรือ AMT103_X4_CWW_3.xlsx']);
end

%% =========================================================
%  อ่านข้อมูล
% ==========================================================

T = readtable(filename,...
    'VariableNamingRule','preserve');

time = double(T.time);

rawCount = double(...
    T.EncoderX4_raw_count);

continuousCount = double(...
    T.continuous_count);

%% =========================================================
%  กำหนดขนาด Timer
% ==========================================================

PERIOD = 65536;
HALF_PERIOD = PERIOD/2;

%% =========================================================
%  หาจุดที่เกิด Wrap-around
% ==========================================================

rawDifference = diff(rawCount);

% จุดที่ Raw count กระโดดมากกว่า 32768
wrapIndexList = find(...
    abs(rawDifference) > HALF_PERIOD);

if isempty(wrapIndexList)

    error('ไม่พบ Wrap-around ในไฟล์ %s',filename);
end

% เลือก Wrap-around จุดแรก
idxWrap = wrapIndexList(1)+1;

fprintf('พบ Wrap-around ที่เวลา %.3f s\n',...
    time(idxWrap));

fprintf('Raw count ก่อน Wrap = %.0f\n',...
    rawCount(idxWrap-1));

fprintf('Raw count หลัง Wrap = %.0f\n',...
    rawCount(idxWrap));

fprintf('Continuous count ก่อน Wrap = %.0f\n',...
    continuousCount(idxWrap-1));

fprintf('Continuous count หลัง Wrap = %.0f\n',...
    continuousCount(idxWrap));

%% =========================================================
%  เลือกช่วงข้อมูลใกล้ Wrap-around
% ==========================================================

% Sample time = 0.001 s
% 1500 samples เท่ากับประมาณ 1.5 วินาที
samplesBefore = 1500;
samplesAfter  = 1500;

idxStart = max(1,...
    idxWrap-samplesBefore);

idxEnd = min(height(T),...
    idxWrap+samplesAfter);

idxPlot = idxStart:idxEnd;

plotTime = time(idxPlot)-time(idxWrap);

rawPlot = rawCount(idxPlot);

continuousPlot = continuousCount(idxPlot);

%% =========================================================
%  สร้าง Figure
% ==========================================================

fig = figure(...
    'Color','white',...
    'InvertHardcopy','off',...
    'Position',[100 70 1150 750]);

tl = tiledlayout(fig,2,1,...
    'Padding','compact',...
    'TileSpacing','compact');

%% =========================================================
%  กราฟที่ 1: Raw Count
% ==========================================================

ax1 = nexttile(tl,1);

stairs(...
    ax1,...
    plotTime,...
    rawPlot,...
    'Color',[0.85 0.10 0.10],...
    'LineWidth',1.8);

hold(ax1,'on');

% เส้นตำแหน่งที่เกิด Wrap-around
xline(...
    ax1,...
    0,...
    '--k',...
    'Wrap-around',...
    'LineWidth',1.3,...
    'LabelVerticalAlignment','bottom');

title(...
    ax1,...
    'AMT103 X4: Raw Count During Timer Underflow',...
    'Color','black',...
    'FontSize',14,...
    'FontWeight','bold');

xlabel(...
    ax1,...
    'Time relative to wrap-around (s)',...
    'Color','black',...
    'FontSize',12);

ylabel(...
    ax1,...
    'Raw count',...
    'Color','black',...
    'FontSize',12);

ylim(ax1,[-2000 67500]);

yticks(ax1,[0 16384 32768 49152 65535]);

grid(ax1,'on');
grid(ax1,'minor');
box(ax1,'on');

%% =========================================================
%  กราฟที่ 2: Continuous Count
% ==========================================================

ax2 = nexttile(tl,2);

plot(...
    ax2,...
    plotTime,...
    continuousPlot,...
    'Color',[0.00 0.30 0.85],...
    'LineWidth',1.8);

hold(ax2,'on');

% เส้นตำแหน่ง Wrap-around
xline(...
    ax2,...
    0,...
    '--k',...
    'Wrap-around',...
    'LineWidth',1.3,...
    'LabelVerticalAlignment','bottom');

% เส้น Count = 0
yline(...
    ax2,...
    0,...
    ':k',...
    'Count = 0',...
    'LineWidth',1.0,...
    'HandleVisibility','off');

title(...
    ax2,...
    'AMT103 X4: Continuous Count After Wrap-around Compensation',...
    'Color','black',...
    'FontSize',14,...
    'FontWeight','bold');

xlabel(...
    ax2,...
    'Time relative to wrap-around (s)',...
    'Color','black',...
    'FontSize',12);

ylabel(...
    ax2,...
    'Continuous count',...
    'Color','black',...
    'FontSize',12);

grid(ax2,'on');
grid(ax2,'minor');
box(ax2,'on');

%% =========================================================
%  บังคับพื้นหลังขาว
% ==========================================================

set(...
    fig,...
    'Color','white',...
    'InvertHardcopy','off');

set(...
    ax1,...
    'Color','white',...
    'XColor','black',...
    'YColor','black',...
    'GridColor',[0.70 0.70 0.70],...
    'MinorGridColor',[0.85 0.85 0.85],...
    'FontSize',11);

set(...
    ax2,...
    'Color','white',...
    'XColor','black',...
    'YColor','black',...
    'GridColor',[0.70 0.70 0.70],...
    'MinorGridColor',[0.85 0.85 0.85],...
    'FontSize',11);

ax1.Title.Color = 'black';
ax1.XLabel.Color = 'black';
ax1.YLabel.Color = 'black';

ax2.Title.Color = 'black';
ax2.XLabel.Color = 'black';
ax2.YLabel.Color = 'black';

%% เชื่อมแกนเวลาเข้าด้วยกัน

linkaxes([ax1 ax2],'x');

%% =========================================================
%  บันทึกภาพ
% ==========================================================

outputName = 'AMT103_X4_WrapAround.png';

exportgraphics(...
    fig,...
    outputName,...
    'Resolution',300,...
    'BackgroundColor','white');

fprintf('บันทึกภาพแล้ว: %s\n',outputName);